homeassistant:

  packages: !include_dir_named packages/
  customize: !include customize.yaml

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  name: Dark Castle

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Activate the configuration editor
config:

automation: !include automations.yaml


