################################################
## Packages / Balcony / Tnx to Cvoid for help ##
## @darkgeej - https://github.com/darkgeej    ##
################################################
homeassistant:
  customize:

    sensor.temperatur_dht_balcony:
      icon: mdi:mdi:temperature-celsius
      friendly_name: Temperatur p책 altanen

    sensor.humidity_dht_balcony:
      icon: mdi:mdi:water-percent
      friendly_name: Fugt p책 altanen

    sensor.lux_balcony:
      icon: mdi:mdi:bulb      
      friendly_name: Lux p책 altanen


##########
# Sensor #
##########
sensor:

  - platform: mqtt
    name: "Temperatur_dht_balcony"
    state_topic: "esp_balcony/dht_balcony/Temperature"
    qos: 0
    unit_of_measurement: "째C"

  - platform: mqtt
    name: "Humidity_dht_balcony"
    state_topic: "esp_balcony/dht_balcony/Humidity"
    qos: 0
    unit_of_measurement: "% Fugt"

  - platform: mqtt
    name: "Lux_balcony"
    state_topic: "esp_balcony/lux_balcony/Lux"
    qos: 0
    unit_of_measurement: "Lux"
