################################################
## Packages / Devices / Tnx to Cvoid for help ##
## @darkgeej - https://github.com/darkgeej    ##
################################################
homeassistant:

media_player:
  - platform: braviatv
    host: !secret braviatv

mqtt:
  broker: !secret mqtthost
  username: !secret mqttuser
  password: !secret mqttpass
  keepalive: 60

tado:
  username: !secret tadouser
  password: !secret tadopass

remote:
  - platform: broadlink
    host: 172.16.5.147
    mac: c8:f7:42:16:a1:81

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomihost
    token: !secret xiaomitoken
