#################################################
## Packages / Entrance / Tnx to Cvoid for help ##
## @darkgeej - https://github.com/darkgeej     ##
#################################################
homeassistant:
  customize:

    sensor.Temperature_littlehall:
      icon: mdi:temperature-celsius       
      friendly_name: Temperatur i stuen

    sensor.Humidity_littlehall:
      icon: mdi:water-percent
      friendly_name: Fugt i stuen

    switch.littlehall_lamp:
      icon: mdi:lightbulb
      friendly_name: Lampe i lille gang


##########
# Sensor #
##########
sensor:

  - platform: mqtt
    name: "Temperature_littlehall"
    state_topic: "esp_littlehall/dht_littlehall/Temperature"
    qos: 0
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Humidity_littlehall"
    state_topic: "esp_littlehall/dht_littlehall/Humidity"
    qos: 0
    unit_of_measurement: "°C"


##########
# Switch #
##########
switch:
  - platform: mqtt
    name: "littlehall_lamp"
    state_topic: "esp_littlehall/lamp_littlehall/gpio/12"
    command_topic: "esp_littlehall/lamp_littlehall/gpio/12"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true


##############
# Automation #
##############
automation:


#Auto turn on #
  - alias: Tænd lyset i gangene 
    trigger:
      platform: numeric_state
      entity_id: sensor.lux_livingroom
      below: 120
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.littlehall_lamp
      - service: light.turn_on
        data: 
          entity_id:
            - light.gangen
          brightness: 140

  - alias: Sluk lyset i gangene
    trigger:
      platform: numeric_state
      entity_id: sensor.lux_livingroom
      above: 120
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.littlehall_lamp
      - service: light.turn_off
        data:
          entity_id:
            - light.gangen
          brightness: 140


# Dim light #
  - alias: "Dim lights at 22.00"
    initial_state: True
    trigger:
      platform: time
      at: '20:00:00'
    action:
      - service: light.turn_on
        entity_id: light.gangen
        data:
          brightness: 75
          transition: 7
