###################################################
## Packages / Livingroom / Tnx to Cvoid for help ##
## @darkgeej - https://github.com/darkgeej       ##
###################################################
homeassistant:
  customize:

    light.retro_lampe:
      icon: mdi:mdi:lightbulb
      friendly_name: Retro lampe

    light.lille_lampe_pa_kommode:
      icon: mdi:mdi:lightbulb
      friendly_name: Lille lampe på kommoden

    light.tradfri_driver:
      icon: mdi:mdi:lightbulb      
      friendly_name: Vitrine skabene

    light.stuen:
      icon: mdi:mdi:lightbulb      
      friendly_name: Væglamperne

    sensor.stuen_temperature_2:
      icon: mdi:temperature-celsius
      friendly_name: Temperaturen i stuen

    sensor.stuen_humidity_2:
      icon: mdi:water-percent
      friendly_name: Fugt i stuen
