#################################################
## Packages / Software / Tnx to Cvoid for help ##
## @darkgeej - https://github.com/darkgeej     ##
#################################################
homeassistant:

sensor:
  - platform: netdata
    resources:
      system_load:
        data_group: system.load
        element: load15
      core0_freq:
        data_group: 'cpu.cpufreq'
        element: 'cpu0'
        icon: mdi:chip

  - platform: moon

# Stats for Unraid
  - platform: systemmonitor
    resources:
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: last_boot

pi_hole:
  - host: !secret pi_hole_ip
    api_key: !secret pi_hole_api_key

recorder:
  purge_keep_days: 5
  db_url: !secret recorder_db_url

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomihost
    token: !secret xiaomitoken
