###############################################
## Packages / Office / Tnx to Cvoid for help ##
## @darkgeej - https://github.com/darkgeej   ##
###############################################
homeassistant:
  customize:

    switch.office_stereo:
      icon: mdi:lightbulb
      friendly_name: Stereo anlæg

    switch.office_minidisc:
      icon: mdi:lightbulb   
      friendly_name: Minidisc

    switch.office_cd:
      icon: mdi:lightbulb   
      friendly_name: Cd afspiller

    switch.office_lp:
      icon: mdi:lightbulb   
      friendly_name: Lp afspiller

    sensor.temperatur_dht_office:
      icon: mdi:temperature-celsius
      friendly_name: Temperaturen i kontoret

    sensor.humidity_dht_office:
      icon: mdi:water-percent
      friendly_name: Fugt i kontoret


    sensor.kontor_temperature_2:
      icon: mdi:water-percent
      friendly_name: Temperaturen i kontoret

    sensor.kontor_humidity_2:
      icon: mdi:water-percent
      friendly_name: Fugt i kontoret


##########
# Switch #
##########
switch:
  - platform: mqtt
    name: "office_stereo"
    state_topic: "esp_office/stereo/gpio/14"
    command_topic: "esp_office/stereo/gpio/14"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true

  - platform: mqtt
    name: "office_minidisc"
    state_topic: "esp_office/minidisc/gpio/12"
    command_topic: "esp_office/minidisc/gpio/12"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true

  - platform: mqtt
    name: "office_cd"
    state_topic: "esp_office/cd/gpio/13"
    command_topic: "esp_office/cd/gpio/13"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true

  - platform: mqtt
    name: "office_lp"
    state_topic: "esp_office/lp/gpio/15"
    command_topic: "esp_office/lp/gpio/15"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true

###########
# WS2812B #
###########


##########
# Sensor #
##########
sensor:

  - platform: mqtt
    name: "Temperatur_DHT_Office"
    state_topic: "esp_office/dht_office/Temperature"
    qos: 0
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Humidity_DHT_Office"
    state_topic: "esp_office/dht_office/Humidity"
    qos: 0
    unit_of_measurement: "% Fugt"

